name: Features - Release
on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref_type == 'branch' && github.ref_name == 'main'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
